### ISSUE TITLE
Validate error on constraint-type column

### ISSUE THREAD

**Issue by pbowen-oc** [enketo/enketo-validate#86]
For items defined with bind::oc:constraint-type = strict, we are getting the following error from Validate:

\n\nFound unsupported oc:constraint-type for question \"temp\". Only numbers 1 to 20 are supported.

Full error:
{
      "code": "XLS_xform_validation_error",
      "message": "\n\nFound unsupported oc:constraint-type for question \"temp\". Only numbers 1 to 20 are supported.
                  \n\nFound unsupported oc:constraint-type for question \"weight\". Only numbers 1 to 20 are supported.
                  \n\nFound unsupported oc:constraint-type for question \"bmi\". Only numbers 1 to 20 are supported.
                  \n\nFound unsupported oc:constraint-type for question \"resp_rate\". Only numbers 1 to 20 are supported.
                  \n\nFound unsupported oc:constraint-type for question \"bp_sys\". Only numbers 1 to 20 are supported.
                  \n\nFound unsupported oc:constraint-type for question \"add_notes\". Only numbers 1 to 20 are supported.
                  \n\nCalculation formula for \"temp_yn_trigger\": Evaluation failed: FormLogicError, Error
                  \n\nCalculation formula for \"bp_dt_prec_trigger\": Evaluation failed: FormLogicError, Error
                  \n\n\n\n"
    },

**Comment by MartijnR** [comment]
fixed in 1.12.0 and I also updated https://validate.enketo.org/oc/

**Comment by pbowen-oc** [comment]
@MartijnR - We're still getting the same errors.

Here is the XLS file we're passing through the new Pyxform to get to Validate:

[demo-vitals-grid-v31.zip](https://github.com/enketo/enketo-validate/files/5403506/demo-vitals-grid-v31.zip)

**Comment by MartijnR** [comment]
* [ ] fix form to not include invisible questions as trigger

**Comment by MartijnR** [comment]
Hmmm. @pbowen-oc could you try with a minimal form and send that? The form you sent has so many errors in it. Would be good to test it here too: https://validate.enketo.org/oc/

**Comment by pbowen-oc** [comment]
@MartijnR - Can you try this one:
[strict constraint test.zip](https://github.com/enketo/enketo-validate/files/5405215/strict.constraint.test.zip)

**Comment by MartijnR** [comment]
I think something went wrong during the update of enketo-validate. This was fixed already.

**Comment by pbowen-oc** [comment]
Looks good in testing
